# ????? ????
  spring.devtools.restart.enabled=true
  spring.thymeleaf.cache=false
  
  # classpath ?? ?? ??(????)
  # poll-interval ?? ?? quiet-period ?? ????.
  spring.devtools.restart.poll-interval=2s
  spring.devtools.restart.quiet-period=1s

server:
  port: 8081